version: '2'
services:
  postgres:
    image: postgres:13
    volumes:
     - ${PWD}/postgresql:/var/lib/postgresql/data
    restart: always
    # osx
    ports:
     - "5443:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust

  redis:
    image: redis:6-alpine
    volumes:
      - ${PWD}/redis:/data
    restart: always
    # osx
    ports:
     - "6380:6379"



