version: '2'
services:
  postgres:
    image: postgres:9.4
    volumes:
     - ${PWD}/postgresql:/var/lib/postgresql/data
    restart: always
    ## linux
    networks:
      openlab:
         ipv4_address: 172.19.0.4
    ## osx
    #ports:
    #  - "5433:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.2
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ${PWD}/elasticsearch:/usr/share/elasticsearch/data
    restart: always
    ## linux
    networks:
      openlab:
        ipv4_address: 172.19.0.2
    ## osx
    #ports:
    #  - "9201:9200"
    #  - "9301:9300"

  kibana:
    image: kibana:5.6
    environment:
      ELASTICSEARCH_HOSTS: http://openlab-elastic:9200
    restart: always
    ## linux
    networks:
      openlab:
        ipv4_address: 172.19.0.5
    ## osx
    #ports:
    #  - "5602:5601"

  redis:
    image: redis:6-alpine
    volumes:
      - ${PWD}/redis:/data
    restart: always
    ## linux
    networks:
      openlab:
        ipv4_address: 172.19.0.3
    ## osx
    #ports:
    #  - "6380:6379"

## linux
networks:
  openlab:
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.0.0/16
          gateway: 172.19.0.1

