version: '2'
services:
  postgres:
    image: postgres:9.4
    volumes:
     - ${PWD}/postgresql:/var/lib/postgresql/data
    restart: always
    # osx
    ports:
     - "5443:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.2
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
      - xpack.security.enabled=true
      - ELASTIC_PASSWORD=openlab
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ${PWD}/elasticsearch:/usr/share/elasticsearch/data
    restart: always
    # osx
    ports:
     - "9202:9200"
     - "9302:9300"

  kibana:
    image: kibana:5.6
    environment:
      ELASTICSEARCH_HOSTS: http://openlab-elastic:9200
    restart: always
    # osx
    ports:
     - "5602:5601"

  redis:
    image: redis:6-alpine
    volumes:
      - ${PWD}/redis:/data
    restart: always
    # osx
    ports:
     - "6380:6379"



